export interface TeamGroup {
  id: string
  groupName: string
  projectTitle: string
  managerName: string
  advisorName: string
  semester: string
  status: "active" | "submitted" | "on-hold"
  members: string[]
  lastActivity: string
}

export const mockTeams: TeamGroup[] = [
  {
    id: "team-alpha",
    groupName: "Group Alpha",
    projectTitle: "AI-Powered Student Assistant",
    managerName: "John Doe",
    advisorName: "Dr. Sarah Johnson",
    semester: "Spring 2024",
    status: "active",
    members: ["John Doe", "Jane Smith", "Bob Wilson"],
    lastActivity: "2024-03-15",
  },
  {
    id: "team-beta",
    groupName: "Group Beta",
    projectTitle: "Blockchain-Based Voting System",
    managerName: "Alice Brown",
    advisorName: "Prof. Michael Chen",
    semester: "Spring 2024",
    status: "submitted",
    members: ["Alice Brown", "Charlie Davis"],
    lastActivity: "2024-03-14",
  },
  {
    id: "team-gamma",
    groupName: "Group Gamma",
    projectTitle: "Smart Campus IoT Platform",
    managerName: "Eva Green",
    advisorName: "Dr. Emily Rodriguez",
    semester: "Spring 2024",
    status: "active",
    members: ["Eva Green", "Frank White", "Grace Lee"],
    lastActivity: "2024-03-16",
  },
  {
    id: "team-delta",
    groupName: "Group Delta",
    projectTitle: "Virtual Reality Lab Simulator",
    managerName: "Henry Ford",
    advisorName: "Prof. David Kim",
    semester: "Spring 2024",
    status: "on-hold",
    members: ["Henry Ford", "Ivy Chen"],
    lastActivity: "2024-03-10",
  },
  {
    id: "team-epsilon",
    groupName: "Group Epsilon",
    projectTitle: "Cloud-Based LMS Integration",
    managerName: "Sophia Turner",
    advisorName: "Dr. Sarah Johnson",
    semester: "Spring 2024",
    status: "active",
    members: ["Sophia Turner", "Liam Carter", "Noah Evans", "Olivia Scott"],
    lastActivity: "2024-03-18",
  },
  {
    id: "team-zeta",
    groupName: "Group Zeta",
    projectTitle: "Predictive Maintenance System",
    managerName: "Mason Brooks",
    advisorName: "Prof. Michael Chen",
    semester: "Spring 2024",
    status: "submitted",
    members: ["Mason Brooks", "Emma Hayes"],
    lastActivity: "2024-03-17",
  },
  {
    id: "team-eta",
    groupName: "Group Eta",
    projectTitle: "Natural Language Processing Chatbot",
    managerName: "Ava Mitchell",
    advisorName: "Dr. Emily Rodriguez",
    semester: "Spring 2024",
    status: "active",
    members: ["Ava Mitchell", "James Parker", "Isabella Reed"],
    lastActivity: "2024-03-19",
  },
  {
    id: "team-theta",
    groupName: "Group Theta",
    projectTitle: "Autonomous Drone Navigation",
    managerName: "Ethan Cooper",
    advisorName: "Prof. David Kim",
    semester: "Spring 2024",
    status: "on-hold",
    members: ["Ethan Cooper", "Mia Rivera", "Lucas Ward", "Charlotte Hughes"],
    lastActivity: "2024-03-08",
  },
  {
    id: "team-iota",
    groupName: "Group Iota",
    projectTitle: "E-Health Monitoring Wearable",
    managerName: "Amelia Foster",
    advisorName: "Dr. Lisa Thompson",
    semester: "Spring 2024",
    status: "active",
    members: ["Amelia Foster", "Benjamin Price"],
    lastActivity: "2024-03-20",
  },
  {
    id: "team-kappa",
    groupName: "Group Kappa",
    projectTitle: "Decentralized File Storage",
    managerName: "Daniel Morris",
    advisorName: "Prof. Michael Chen",
    semester: "Spring 2024",
    status: "submitted",
    members: ["Daniel Morris", "Harper Sanders", "Elijah Jenkins", "Abigail Perry"],
    lastActivity: "2024-03-13",
  },
  {
    id: "team-lambda",
    groupName: "Group Lambda",
    projectTitle: "AR Campus Navigation App",
    managerName: "Logan Bell",
    advisorName: "Dr. Emily Rodriguez",
    semester: "Spring 2024",
    status: "active",
    members: ["Logan Bell", "Chloe Cox", "Jackson Richardson"],
    lastActivity: "2024-03-21",
  },
  {
    id: "team-mu",
    groupName: "Group Mu",
    projectTitle: "Gamified Learning Platform",
    managerName: "Grace Wood",
    advisorName: "Dr. Sarah Johnson",
    semester: "Spring 2024",
    status: "on-hold",
    members: ["Grace Wood", "Sebastian Russell"],
    lastActivity: "2024-03-05",
  },
]

